[package]
name = "proof_of_audit"
version = "0.1.0"
description = "Created with Web3 Guard to anchor rust contract audits to Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "proof_of_audit"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
